home/urls.py
from typing import Pattern
from django import urls
from django.urls import path
from django.shortcuts import render, redirect
from home.views import *


#Urls de direccionamiento dentro de la app
urlpatterns = [
    path('', index, name='index'),
    path('proyectos', proyectos, name='proyectos'),
    path('podcast', podcast, name='podcast'),
    path('register', register, name='register'),
    path('proyecto_detail/<int:pk>', proyecto_detail, name='proyecto_detail'),
    path('contactos/', contactos, name='contactos'),
    path('blog/<int:pk>', blog, name='blog'),
    path('list_blog', list_blog, name='list_blog'),

]

jolrobles/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('',include(('apps.app_pos_kirios.urls',''))),
    path(r'', include(('home.urls','home'), namespace ='home')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models
from django.utils.timezone import now
from django.contrib.auth.models import User
import datetime
# Create your models here.
# Create your models here.
class Blog(models.Model):
    imagen_portada = models.TextField(null = True, blank = True)
    titulo = models.CharField(max_length=200)
    imagen = models.TextField(null = True, blank = True)
    imagen_2 = models.TextField(null = True, blank = True)
    detalle_principal = models.TextField(null=True, blank=True)
    detalle = models.TextField(null=True, blank=True)
    fecha = models.DateField(default=now)
    autor = models.ForeignKey(User, on_delete=models.CASCADE,)
    activo = models.BooleanField(default=True)

    class Meta:
        verbose_name='Blog'
        verbose_name_plural='Blogs'
    def __str__(self):
        return self.titulo

class Proyecto(models.Model):
    TIPO_PROYECTO = [
        ('S','Software'),
        ('D','Diseño'),
        ('F','Fotografía'),
    ]
    nombre = models.CharField(max_length=200)
    imagen = models.TextField(null=True, blank=True)
    rol_realizado = models.CharField(max_length=200, null=True, blank=True)
    descripcion = models.TextField(null=True, blank=True)
    link = models.URLField(null=True, blank=True)
    empresa = models.CharField(max_length=200)
    tipo_proyecto = models.CharField(blank=True, null=True, choices=TIPO_PROYECTO, max_length=50)
    activo = models.BooleanField(default=True)

    class Meta:
        verbose_name='Proyecto'
        verbose_name_plural='Proyectos'
    def __str__(self):
        return self.nombre
    
class QuienSoy(models.Model):
    img_perfil = models.ImageField(null=True, blank=True)
    titulo = models.CharField(max_length=200)
    descripcion = models.TextField(null=True, blank=True)
    class Meta:
        verbose_name='QuienSoy'
        verbose_name_plural='QuienSoy'
    def __str__(self):
        return self.titulo
    

class RespuestaBlog(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, null=True, blank=True)
    nombre = models.CharField(max_length=200)
    email = models.EmailField()
    comentario = models.TextField(null=True, blank=True)
    fecha_hora = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name='RespuestaBlog'
        verbose_name_plural='RespuestasBlog'
    def __str__(self):
        return self.nombre

home/forms.py
from django import forms
from django.db.models import fields

from .models import *

class RespuestaBlogForm(forms.ModelForm):
    """Form definition for Detalle."""

    class Meta:
        """Meta definition for Detalleform."""

        model = RespuestaBlog
        fields = '__all__'
        exclude = [
            'blog'
        ]
        widgets = {
            'comentario': forms.Textarea(attrs={'rows': '3'}),
        }

home/views.py
from django.shortcuts import render
from .models import *
from .forms import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.shortcuts import render, redirect
from django.contrib import messages
# Create your views here.
def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            # user = form.save()
            # user.is_staff = True
            # user.is_superuser = True
            # user.active = True
            # user.save()
            # Iniciar sesión al usuario después del registro
            # login(request, user)
            return redirect('home:list_blog')  # Cambia 'home' por el nombre de tu vista de inicio
    else:
        form = UserCreationForm()
    context = { 
        'title':"Register",
        'form':form
    }
    return render(request, 'home/register.html', context)

def index(request):
    quien_soy = QuienSoy.objects.filter()
    context = {
        'quien_soy':quien_soy
    }
    return render(request, 'index.html', context)

def proyectos(request):
    proyectos = Proyecto.objects.filter(activo=True)
    context = {
        'proyectos':proyectos
    }
    return render(request, 'home/proyectos.html', context)

def podcast(request):
    # proyectos = Proyecto.objects.filter(activo=True)
    context = {
        'proyectos':'proyectos'
    }
    return render(request, 'home/podcast.html', context)

def proyecto_detail(request, pk):
    proyecto = Proyecto.objects.get(pk=pk)
    proyectos = Proyecto.objects.filter(activo=True)
    context = {
        'proyecto':proyecto,
        'proyectos':proyectos
    }
    return render(request, 'home/proyecto_detail.html', context)

def contactos(request):

    return render(request, 'home/contacto.html')


def blog(request, pk):
    blog_object = Blog.objects.get(pk=pk)
    respuestas = RespuestaBlog.objects.filter(blog=blog_object)
    blogs = Blog.objects.all()
    respuesta_formulario = RespuestaBlogForm()
    if request.method == 'POST':
        respuesta_formulario = RespuestaBlogForm(request.POST, request.FILES)
        if respuesta_formulario.is_valid():
            respuesta = respuesta_formulario.save(commit=False)
            respuesta.blog = blog_object
            respuesta.save()
            messages.success(request, f'Respuesta Creada, ¡Muchas gracias!')
            return redirect('home:blog', blog_object.pk)
        else:
            context = {
                'blog_object':blog_object,
                'blogs':blogs,
                'respuesta_form':respuesta_formulario,
                'respuestas':respuestas,
            }
            messages.error(request, 'Corrija los errores')
            print(respuesta_formulario.errors)
            return render(request, 'home/blog.html', context)
    context = {
        'blog_object':blog_object,
        'blogs':blogs,
        'respuesta_form':respuesta_formulario,
        'respuestas':respuestas
    }
    return render(request, 'home/blog.html', context)

def list_blog(request):
    blogs = Blog.objects.filter(activo=True)
    context = {
        'blogs':blogs
    }
    return render(request, 'home/blog_list.html', context)

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

  <head>
    <title>
      JolRobles -
      {% block title %}
      {% endblock title %}
    </title>
    {% block meta %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    {% endblock meta %}
    {% block stylesheets %}

    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400;500;600;700&display=swap" rel="stylesheet">

      <!-- Additional CSS Files -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.css' %}">

    <link rel="stylesheet" href="{% static 'css/templatemo-klassy-cafe.css' %}">

    <link rel="stylesheet" href="{% static 'css/owl-carousel.css' %}">

    <link rel="stylesheet" href="{% static 'css/lightbox.css' %}">
    <!-- Favicon -->
    <link rel="shortcut icon" type="image/x-icon" href="{% static '/images/jolrobles.ico' %}">
    <!-- FAVICONS -->
    <link rel="apple-touch-icon" href="{% static '/images/logo_blanco_vertical.png' %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static '/images/72x72.png' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static '/images/114x114.png' %}">

    {% endblock stylesheets %}
  </head>
  <!-- Google tag (gtag.js) -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-LVL2ERM8H2"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'G-LVL2ERM8H2');
  </script>

  <body>

  {% block header %}
        {% include "header.html" %}
  {% endblock header %}

  {% block content %}
  {% endblock content %}

  {% block footer %}
        {% include "footer.html" %}
  {% endblock footer %}

  {% block scripts %}

      <!-- jQuery -->
      <script src="{% static 'js/jquery-2.1.0.min.js' %}"></script>

      <!-- Bootstrap -->
      <script src="{% static 'js/popper.js' %}"></script>
      <script src="{% static 'js/bootstrap.min.js' %}"></script>

      <!-- Plugins -->
      <script src="{% static 'js/owl-carousel.js' %}"></script>
      <script src="{% static 'js/accordions.js' %}"></script>
      <script src="{% static 'js/datepicker.js' %}"></script>
      <script src="{% static 'js/scrollreveal.min.js' %}"></script>
      <script src="{% static 'js/waypoints.min.js' %}"></script>
      <script src="{% static 'js/jquery.counterup.min.js' %}"></script>
      <script src="{% static 'js/imgfix.min.js' %}"></script>
      <script src="{% static 'js/slick.js' %}"></script>
      <script src="{% static 'js/lightbox.js' %}"></script>
      <script src="{% static 'js/isotope.js' %}"></script>

      <!-- Global Init -->
      <script src="{% static 'js/custom.js' %}"></script>
      <script type="text/javascript">
        function itemSelected(element){
          $element = element
          $element.style = "border: solid !important; border-top-width: 10px; border-right-width:0px; border-bottom-width:0px; border-left-width:0px "
          $element.className = "active"
        }
      </script>
  {% endblock scripts %}

    </body>
  </html>

templates/footer.html
<!-- ***** Footer Start ***** -->
{% load static %}
<footer>
    <div class="container" style="max-width:1440px">
        <div class="row">
          <div class="col-md-3 col-xs-3" style="width: 50%; margin-top: 5px;margin-bottom: 5px; display: flex; justify-content: center; align-items: center;">
            <a href="index.html"><img src="{% static 'images/logo_blanco_vertical.png' %}" alt="" style="max-width: 100px;"></a>
          </div>
          <div class="col-md-3 col-xs-3" style="width: 50%; margin-top: 5px;margin-bottom: 5px;">
            <p  style="color:#fff"><b>MENÚ PRINCIPAL</b></p>
            <a href="{% url 'home:index' %}" style="color:#fff">INICIO </a><br>
            <a href="{% url 'home:proyectos' %}" style="color:#fff">PROYECTOS</a><br>
            <a href="{% url 'home:index' %}" style="color:#fff">BLOG</a><br>
          </div>
          <div class="col-md-3 col-xs-3" style="width: 50%; margin-top: 5px;margin-bottom: 5px;">
            <p  style="color:#fff"><b>REDES SOCIALES</b></p>
            <ul class="social-icons">
                <li style="color:#fff"><a target="_blank" href="https://www.facebook.com/jolrobless"><i class="fa fa-facebook"></i></a> Facebook</li>
            </ul>
            <ul class="social-icons">
              <li style="color:#fff"><a target="_blank" href="https://www.linkedin.com/in/jolrobles/"><i class="fa fa-linkedin"></i></a> Linkedin</li>
            </ul>
            <ul class="social-icons">
              <li style="color:#fff"><a target="_blank" href="https://www.instagram.com/jolrobles/"><i class="fa fa-instagram"></i></a> Instagram</li>
            </ul>
          </div>
            <div class="col-md-3 col-xs-3" style="width: 50%; margin-top: 5px;margin-bottom: 5px;">
                <p style="color:#fff"><b>CONTACTO</b></p>
                <ul class="social-icons">
                  <li style="color:#fff"><a target="_blank" href="https://wa.me/593981538762/?"><i class="fa fa-whatsapp"></i></a> 0981538762</li>
                </ul>
                <ul class="social-icons">
                  <li style="color:#fff"><a target="_blank" href="https://wa.me/593981538762/?"><i class="fa fa-envelope"></i></a> jolrobles5@gmail.com</li>
                </ul>
            </div>
        </div>
    </div>
</footer>

templates/header.html
{% load static %}
    <!-- ***** Header Area Start ***** -->
    <header class="header-area header-sticky">
        <div class="container" style="max-width:1440px">
            <div class="row">
                <div class="col-12">
                    <nav class="main-nav">
                        <!-- ***** Logo Start ***** -->
                        <a href="{% url 'home:index' %}" class="logo">
                            <img src="{% static 'images/logooo1.gif' %}" style="max-width: 200px; margin-left: 20px;">
                        </a>
                        <!-- ***** Logo End ***** -->
                        <!-- ***** Menu Start ***** -->
                        <ul class="nav">
                          <!-- <li id='seccion' onclick="itemSelected(this)"  style="border: solid; border-top-width: 10px; border-right-width:0px; border-bottom-width:0px; border-left-width:0px "><a href="{% url 'home:index' %}">INICIO</a></li> -->
                            <li id='seccion' onclick="itemSelected(this)"   ><a href="{% url 'home:index' %}">INICIO</a></li>
                            <li onclick="itemSelected(this)"><a href="{% url 'home:podcast' %}">PODCAST</a></li>
                            <li onclick="itemSelected(this)"><a href="{% url 'home:proyectos' %}">PORTAFOLIO</a></li>
                            <li onclick="itemSelected(this)"><a href="{% url 'home:list_blog' %}">BLOG</a></li>
                            <!-- <li onclick="itemSelected(this)"><a href="{% url 'home:register' %}">Register</a></li> -->
                            <!-- <li onclick="itemSelected(this)"><a href="{% url 'home:contactos' %}">CONTACTO</a></li> -->
                        </ul>
                        <a class='menu-trigger'>
                            <span>Menu</span>
                        </a>
                        <!-- ***** Menu End ***** -->
                    </nav>
                </div>
            </div>
        </div>
    </header>

    <!-- ***** Header Area End ***** -->

templates/home/blog_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
BLOG
{% endblock title %}
{% block content %}
    <!-- **** * About Area Starts ***** -->
    <section class="section" id="about">
        <div class="container" style="max-width:1440px">
          <div class="text-center pb-2">
            <h3 class="mb-4">Que la lectura sea un hábito que fomentemos a diario</h3>
          </div>
          <div class="row">
          {% for blog in blogs %}
          <div class="col-md-4" style="padding-top: 15px;" >
            <a href="{% url 'home:blog' blog.pk %}">
              <div class="position-relative">
                <img src="{{blog.imagen_portada}}" style="border-top-left-radius: 20px; border-top-right-radius: 20px; max-width:300; max-height:300" alt="">
                <div class="portfolio-btn bg-dark d-flex align-items-center justify-content-center text-center" style="margin-top: 0px;">
                  <h5 class="text-white" style="font-size: 50px">{{blog.titulo}}</h5>
                </div>
              </div>
            </a>
          </div>
          {% endfor %}
        </div>
        </div>
    </section>
    <!-- ***** About Area Ends ***** -->
    {% endblock content %}
{% block scripts %}
{{block.super}}
<script src="https://unpkg.com/isotope-layout@3/dist/isotope.pkgd.js"></script>
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
<script src="{% static 'lib/easing/easing.min.js' %}"></script>
<script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>
<script src="{% static 'lib/isotope/isotope.pkgd.min.js' %}"></script>
<script src="{% static 'lib/lightbox/js/lightbox.min.js' %}"></script>

<!-- Template Javascript -->
<script src="{% static 'js/main.js' %}"></script>

{% endblock scripts %}

templates/home/proyectos.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
PROYECTOS
{% endblock title %}
{% block content %}
<section class="section" id="about">
    <!-- Gallery Start -->
    <div class="container-fluid ">
      <div class="container" style="max-width:1440px">

        <div class="row center" style="justify-content: center;">
          <div class="col-md-8 col-xs-12 text-center mb-2"  style="background-color:#000000; border-radius:20px">
            <ul class="list-inline" id="portfolio-flters" style="margin-top: 10px; margin-bottom: 10px;">
              <li class="btn btn-outline-dark m-1 active" data-filter="*" style="color:#fff; border:0px">
                Todos
              </li>
              <li class="btn btn-outline-dark m-1" data-filter=".first" style="color:#fff; border:0px">
                Software
              </li>
              <li class="btn btn-outline-dark m-1" data-filter=".second" style="color:#fff; border:0px">
                Diseño
              </li>
            </ul>
          </div>
        </div>
        <div class="text-center pb-2">
          <h1 class="mb-4">Portafolio</h1>
        </div>
        <div class="row portfolio-container">
          {% for proyecto in proyectos %}
            {% if proyecto.tipo_proyecto == 'S' %}
            <div class="col-lg-4 col-md-6 mb-4 portfolio-item first">
            {% elif proyecto.tipo_proyecto == 'D' %}
            <div class="col-lg-4 col-md-6 mb-4 portfolio-item second">
              {% else %}
            <div class="col-lg-4 col-md-6 mb-4 portfolio-item third"></div>
            {% endif %}
              <a href="{% url 'home:proyecto_detail' proyecto.pk %}" >
                <div class="position-relative overflow-hidden mb-2">
                  <img src="{{proyecto.imagen}}" style="border-top-left-radius: 20px; border-top-right-radius: 20px;" alt="">
                  <div class="portfolio-btn bg-dark d-flex align-items-center justify-content-center text-center" style="margin-top: 0px;">
                    <h5 class="text-white" style="font-size: 20px">{{proyecto.nombre}}  
                    <p class="text-white">{{proyecto.rol_realizado}}</p>
                    </h5>
                  </div>
                </div>
              </a>
            </div>
          {% endfor %}
        </div>
      </div>
    </div>
    <!-- Gallery End -->

    </section>
    {% endblock content %}
{% block scripts %}
{{block.super}}
<script src="https://unpkg.com/isotope-layout@3/dist/isotope.pkgd.js"></script>
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
<script src="{% static 'lib/easing/easing.min.js' %}"></script>
<script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>
<script src="{% static 'lib/isotope/isotope.pkgd.min.js' %}"></script>
<script src="{% static 'lib/lightbox/js/lightbox.min.js' %}"></script>

<!-- Template Javascript -->
<script src="{% static 'js/main.js' %}"></script>
<script type="text/javascript">
  function CambiaColor(element){
    $element = element.parentElement
    let parent = $element.querySelector(`img[id="parent"]`);
    parent.style = 'height:250px; border-top-left-radius: 20px; border-top-right-radius: 20px; filter: grayscale(0%)';
  }
  function CambiaNegro(element){
    $element = element.parentElement
    let parent = $element.querySelector(`img[id="parent"]`);
    parent.style = 'height:250px; border-top-left-radius: 20px; border-top-right-radius: 20px; filter: grayscale(100%)';
  }
</script>
{% endblock scripts %}

templates/home/register.html
<h2>Registro de Usuario</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Registrarse</button>
  </form>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
INICIO
{% endblock title %}
{% block content %}

    <!-- ***** About Area Starts ***** -->
    <section class="section" id="about">
        <div class="container" style="max-width:1440px">
            <div class="row">
              {% for item in quien_soy %}
              <div class="col-lg-4 col-md-4 col-xs-12">
                <div style="display: flex; justify-content: center; align-items: center;">
                  <img  style="border-radius:50%; max-width: 300px;" class="parent" id="parent" src="{% static 'images/perfil.jpg' %}" alt="">
                </div>
                <div>
                  <p class="text-center" style="line-height:15px; margin:5px"> El éxito llega para todos aquellos que <br>estan ocupados buscándolo</p>
                </div>
              </div>
                <div class="col-lg-8 col-md-8 col-xs-12">
                  <div class="left-text-content">
                    
                      <div class="section-heading">
                          <h2>{{item.titulo}}</h2>
                      </div>
                      <p style="text-align:justify" >{{item.descripcion|linebreaks}}</p>
                  </div>
                  REDES SOCIALES
                  <div class="row">
                    <li style="color:#fff; font-size: 30px; padding: 10px;"><a target="_blank" href="https://www.facebook.com/jolrobless"><i class="fa fa-facebook"></i></a></li>
                    <li style="color:#fff; font-size: 30px; padding: 10px;"><a target="_blank" href="https://www.instagram.com/jolrobles/"><i class="fa fa-instagram"></i></a></li>
                    <li style="color:#fff; font-size: 30px; padding: 10px;"><a target="_blank" href="https://www.tiktok.com/@jolrobles?_t=8nSUJZzM0la&_r=1">
                    <svg style="width: 25px; height: 25px; fill:#007bff" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path d="M448 209.9a210.1 210.1 0 0 1 -122.8-39.3V349.4A162.6 162.6 0 1 1 185 188.3V278.2a74.6 74.6 0 1 0 52.2 71.2V0l88 0a121.2 121.2 0 0 0 1.9 22.2h0A122.2 122.2 0 0 0 381 102.4a121.4 121.4 0 0 0 67 20.1z"/></svg>
                    </a></li>
                    <li style="color:#fff; font-size: 30px; padding: 10px;"><a target="_blank" href="https://www.youtube.com/@JolRobles"><i class="fa fa-youtube"></i></a></li>
                    <li style="color:#fff; font-size: 30px; padding: 10px;"><a target="_blank" href="https://podcasters.spotify.com/pod/show/jolrobles"><i class="fa fa-spotify"></i></a></li>
                    <li style="color:#fff; font-size: 30px; padding: 10px;"><a target="_blank" href="https://api.whatsapp.com/send/?phone=593981538762&text&type=phone_number&app_absent=0"><i class="fa fa-whatsapp"></i></a></li>
                  </div>
                  
                </div>
                    
              {% endfor %}
            </div>
        </div>
    </section>
    <!-- ***** About Area Ends ***** -->
    <div class="text-center" style="margin:20px">
      <h2>SECCIONES</h2>
    </div>
    <!-- ***** Menu Area Starts ***** -->
    <section class="section" id="menu">
      <div class="content">
        <div class="row">
          
          <div class="col-md-3" style="padding-top: 10px;">
            <a href="{% url 'home:podcast' %}">
              <div class='card card2'>
                <div class='info'>
                  <h1 class='title'>PODCAST</h1>
                  <p class='description'>ENTREVISTAS<br>HISTORIAS <br>APRENDIZAJES <br>VIDA COTIDIANA<br>SUPERACIÖN</p>
                </div>
              </div>
            </a>
          </div>
          <div class="col-md-3" style="padding-top: 10px;">
            <a href="{% url 'home:proyectos' %}">
              <div class='card card1'>
                <div class='info'>
                  <h1 class='title'>DESARROLLO</h1>
                  <p class='description'>Python - Django <br>JavaScript - Flutter <br>NodeJs - Angular <br>Git - Html - Css <br>SO: Windows - Linux</p>
                </div>
              </div>
            </a>
          </div>
          <div class="col-md-3" style="padding-top: 10px;">
            <a href="{% url 'home:proyectos' %}">
              <div class='card card3'>
                <div class='info'>
                  <h1 class='title'>DISEÑO</h1>
                  <p class='description'>PHOTOSHOP<br>ILUSTRADOR<br>PREMIER<br>AUDITION<br>MARCAS</p>
                </div>
              </div>
            </a>
          </div>
          <div class="col-md-3" style="padding-top: 10px;">
            <a href="{% url 'home:list_blog' %}">
              <div class='card card4'>
                <div class='info'>
                  <h1 class='title'>BLOGS</h1>
                  <p class='description'>EXPERIENCIAS<br>CONOCIMIENTOS<br>FAMILIA<br>PERSAMIENTOS<br>SUEÑOS</p>
                </div>
              </div>
            </a>
          </div>
        </div>
      </div>


        <div class="text-center" style="margin:30px; margin-block-end:0px">
          <img src="{% static 'images/logo_blanco.png' %}">
        </div>
    </section>
    <!-- ***** Menu Area Ends ***** -->

    <div class="text-center" style="margin-top:80px">
        <h1>Que tus talentos sean para servir a los demás</h1>
    </div>
{% endblock content %}
{% block scripts %}
{{block.super}}
<script type="text/javascript">
  let parent = document.getElementById('parent');
  console.log(parent);
  parent.addEventListener('mouseover', function() {
    parent.style = 'border-radius:50%;  filter: grayscale(0%);  max-width: 300px;';
  })
  parent.addEventListener('mouseout', function() {
    parent.style = 'border-radius:50%;  filter: grayscale(100%);  max-width: 300px;';
  })
</script>
<script type="text/javascript">
  function CambiaColor(element){
    console.log(element);
    $element = element.parentElement
    console.log($element);
    let parent = $element.querySelector(`div[id="parent"]`);
  }
  function CambiaNegro(element){
    $element = element.parentElement
    let parent = $element.querySelector(`div[id="parent"]`);
  }
</script>
{% endblock scripts %}